### ISSUE TITLE
[Bug] Save new name 

### ISSUE THREAD

**Issue by M-u-e-c-k-e** [jethornton/7i95#8] opened 2022-04-14 10:12 UTC
-- en --
1. i change the configuration 
2. i change the name "configuration name 
3. configuration checked
` Configuration checked OK`
5. build configuration 
```
Building /home/cnc/linuxcnc/configs/scala_2/scala_2.ini
Building /home/cnc/linuxcnc/configs/scala_2/scala_2.hal
Building /home/cnc/linuxcnc/configs/scala_2/io.hal
```
There is only the file `scala_2.ini`
The files  (`io.hal` and `scala_2.hal`)have not been built. 

6. Again "Build Configuration "
Now all files exist.

Greetings 

Translated with www.DeepL.com/Translator (free version)

-- de --
1. Ich ändere die Konfiguration. 
2. Ich ändere den Namen "Configuration Name" 
3. Configuration checked
` Configuration checked OK`
5. Build Configuration 
```
Building /home/cnc/linuxcnc/configs/scala_2/scala_2.ini
Building /home/cnc/linuxcnc/configs/scala_2/scala_2.hal
Building /home/cnc/linuxcnc/configs/scala_2/io.hal
```
Es existiert nur die Datei `scala_2.ini`
Die Dateien (`io.hal` und `scala_2.hal`) wurden nicht erstellt. 

6. noch mal "Build Configuration "
Jetzt existieren alle Dateien.

Gruß

**Comment by jethornton** [comment] 2022-04-14 13:46
What was the first configuration name and the next name?
I can not duplicate that behavior here

**Comment by M-u-e-c-k-e** [comment] 2022-04-14 14:00
-- en -- 
no problem, unfortunately I can not make a video from the monitor, therefore pictures ;-). 
I hope you understand what I did. and what the result is. 
1. configuration I have attached with. 

-- de -- 
kein Problem, leider kann ich kein Video vom Monitor machen, daher Bilder ;-). 
Ich hoffe man versteht was ich gemacht habe. und was das Ergebnis ist. 
1. Konfiguration habe ich mit angehängt. 


Step 1
![001](https://user-images.githubusercontent.com/103420027/163406290-bd0bdf37-097c-4f06-bdf5-ad182f432fba.png)
Step 2
![002](https://user-images.githubusercontent.com/103420027/163406358-721a123b-82ec-4c61-b7d1-f6cacda79c9c.png)
Step 3
![003](https://user-images.githubusercontent.com/103420027/163406388-ad3c3301-2dd9-4c2d-9036-70445fcaa50c.png)
Step 4 
![004](https://user-images.githubusercontent.com/103420027/163406436-9deb0ff3-ddce-4804-8c7a-a463260d9f7f.png)

Konfiguration of Start: 
[x-achse.zip](https://github.com/jethornton/7i95/files/8489716/x-achse.zip)

**Comment by jethornton** [comment] 2022-04-14 17:12
I can not reproduce that behavior here.

**Comment by jethornton** [comment] 2022-04-14 19:44
I tried to reproduce that behaviour on 2 more Debian PC's and can not duplicate what you see.

What OS are you using?

**Comment by jethornton** [comment] 2022-04-14 20:03
I suspect the file manager you are using does not update well.

**Comment by M-u-e-c-k-e** [comment] 2022-04-15 09:56
> What OS are you using?
I use the ISO from LinuxCNC.org
http://linuxcnc.org/downloads/ ==> LinuxCNC 2.8.2 [Debian 10 Buster PREEMPT-RT ISO](http://www.linuxcnc.org/iso/linuxcnc-2.8.2-buster.iso)

> I suspect the file manager you are using does not update well, I use Caja.
How can I view this? 
I have the one that comes with the system. 

If you tell me what software makes videos from the monitor, I would install that and make a video, maybe that will help?

**Comment by jethornton** [comment] 2022-04-15 10:12
A video of your system won't help because the issue is not with my 7i95 Configuration Tool, the issue is with your file manager. So I'm closing this issue.

**Closed by jethornton** 2022-04-15 10:12 UTC
